stages:
    - deploy

pages:
    stage: deploy
    image: alpine:latest
    variables:
        FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"
    script:
        - apk add nodejs brotli
        - node generate-index.js
        - node generate-brotli.js
        - mkdir .public
        - cp -r * .public
        - mv .public public
    artifacts:
        paths:
            - public
